### ISSUE TITLE
Placeholder missing

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [Kombustor/antd-password-input-strength#1]
Hey man, this is wonderful, thank you! But how do you pass a placeholder? I tried and it doesn't show up

**Comment by Kombustor** [comment]
Hey @AndreaPontrandolfo 

You have to pass properties for the Input-component via inputProps:
`
<PasswordInput 
  inputProps={{
    placeholder: "Password"
  }}
/>
`

**Comment by AndreaPontrandolfo** [comment]
For some reason i tried this same code yesterday and it wouldn't work. Now i copy/pasted your snippet and it works. I don't know, i'm dumb. Thanks for the help, this is great, keep it up!
