### ISSUE TITLE
Prevent sending unsecure passwords on submit

### ISSUE THREAD

**Issue by bennik88** [Kombustor/antd-password-input-strength#22]
**Problem**
There is no option to validate the form with the password strength at the moment. So for displaying how strong the password is it seems great. But there seems no way to prevent the user from sending insecure passwords. Or am I missing something?

**Solution**
A property for props like `validation=true || false` which toggles the validation of the password and prevents it from sending if unsecure.

**Comment by Kombustor** [comment]
Hello @bennik88 

I just published version `2.0.1` and added a validation example to the README!
